name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
 Check failure on line 8 in .github/workflows/indexmain.yml

GitHub Actions
/ .github/workflows/indexmain.yml
Invalid workflow file
You have an error in your yaml syntax on line 8
    - run: |
          jar cvf groupe5.war * && ls
      - name: copy file via ssh password
      - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "groupe5.war"
        target: "/opt/tomcat/webapps"
